### ISSUE TITLE
Links in README.md are down

### ISSUE THREAD

**Issue by ncalexan** [taskcluster/taskcluster-client.py#120]
For example, https://github.com/taskcluster/taskcluster-client.py#get-task-definition links "Output schema" to https://github.com/taskcluster/taskcluster-client.py/blob/master/v1/task.json# -- which doesn't exist.

**Comment by djmitche** [comment]
It looks like this is still an issue.  There is no canonical location for schema files.  I think the better plan would be to construct a link to the docs for that API method, which will include the schemas.

**Comment by djmitche** [comment]
https://github.com/taskcluster/taskcluster-client.py/pull/125#issuecomment-468755868
> I'm guessing we're removing these because of at least one/some of the following reasons?
> 
>     * r14y breaks some assumptions about where the docs are
> 
>     * tc.py hasn't been updated for a while, and the apis have changed enough that the links were old
> 
>     * other ?
> 
> 
> I think this approach works for removing the links, although strings like `This exchange has outputs` are a bit awkward.
> 
> I'm wondering if the best approach is removing the links, or fixing them in an r14y world.
