### ISSUE TITLE
Documentation for credentials is out-of-date

### ISSUE THREAD

**Issue by mitchhentges** [taskcluster/taskcluster-client.py#123]
The documentation has a section for [creating temporary credentials](https://github.com/taskcluster/taskcluster-client.py#generating-temporary-credentials), but running `taskcluster.createTemporaryCredentials(...)` yields the error:

> `AttributeError: module 'taskcluster' has no attribute 'createTemporaryCredentials'`

I'm guessing that `createTemporaryCredentials` is a Taskcluster < 5 function?

**Comment by escapewindow** [comment]
You might want `taskcluster.client.createTemporaryCredentials` or `taskcluster.aio.asyncclient.createTemporaryCredentials`. We should probably update the docs.

**Comment by mitchhentges** [comment]
In my case, I added `"credentials": {"clientId": ..., "accessToken": ...}` to my config, and it happily worked :)
