### ISSUE TITLE
Provide wheel distribution on PyPI

### ISSUE THREAD

**Issue by edmorley** [taskcluster/taskcluster-client.py#79]
Hi!

Please could this package also by made available as a wheel on PyPI?
https://pypi.python.org/pypi/taskcluster/1.3.4

Wheels have the following advantages:
* Faster installation time
* Allows the wheel cache to work even when using the new pip hash-checking mode
* Allows tools to statically inspect the package metadata without having to execute untrusted code.
* ...and more - see: http://pythonwheels.com

This package is pure Python and supports both Python 2 and 3, so in theory could be distributed as a "universal wheel":
https://packaging.python.org/tutorials/distributing-packages/#wheels

...however I notice that there's some Python 3 customisation of `install_requires` going on here:
https://github.com/taskcluster/taskcluster-client.py/blob/bf8b46bf756c528dc5b0a8f6476cef7739c5e8ce/setup.py#L66-L70

...which means separate wheels have to be generated for each of Python 2 and 3. 

(An alternative would be to use the special `extras_requires` syntax [documented here](https://wheel.readthedocs.io/en/latest/#defining-conditional-dependencies), in which case ignore the instructions below and instead follow the universal wheel steps in taskcluster/slugid.py#6.)

The Python packaging guide recommends using [Twine](https://github.com/pypa/twine) to upload packages:
https://packaging.python.org/tutorials/distributing-packages/#uploading-your-project-to-pypi

As such, the steps for building/uploading a new release are then:

```bash
$ pip2 install -U twine setuptools wheel
$ pip3 install -U setuptools wheel
$ rm -rf dist/ build/
$ python2 setup.py sdist bdist_wheel
# Work around https://bitbucket.org/pypa/wheel/issues/147/bdist_wheel-should-start-by-cleaning-up
$ rm -rf build/
$ python3 setup.py bdist_wheel
$ twine upload dist/*
```

The PyPI package listing will then display three entries for the new release, one with type "Source" and two of type "Python Wheel" (one for each of Python 2 and 3).

Many thanks :-)

**Comment by edmorley** [comment]
I guess as an added bonus, setup.py could omit `taskcluster.async` from the `packages` property on Python 2, so that the async directory isn't bundled in the Python 2 wheel.

**Comment by edmorley** [comment]
> so that the async directory isn't bundled in the Python 2 wheel.

I think it makes sense to do this, which means we'll need separate Python 2 and Python 3 wheels anyway, so let's not bother converting to the alternative extras_requires syntax.

**Comment by jhford** [comment]
Hi Ed,  I'm not sure when I'll have a chance to work on this, but I'm happy to review patches if you find yourself with time to work on it.  My only request is that the release.sh script continue to work, that running unit tests can be done either through the make file or `tox` on the command line and that the unit tests ensure that both wheel and non-wheel packaging work as expected.

**Comment by edmorley** [comment]
I'm working on a PR at the moment :-)
