### ISSUE TITLE
Document taskcluster vs taskcluster.async in the README

### ISSUE THREAD

**Issue by edmorley** [taskcluster/taskcluster-client.py#81]
On Python 3 only, there's an asynchronous API available in the form of `taskcluster.async`.

However the readme currently doesn't explicitly state that it exists (it's just mentioned in passing in some examples), and that it's Python 3 only.

(On that note, it's probably worth also mentioning in the readme that the minimum Python 3 version is 3.5)

**Comment by jhford** [comment]
Hey @escapewindow I think you wrote the majority of the async parts of the client and have the most context for them.  Do you think you'd have a moment to add this section to the `README.md` file?  Maybe in addition to Ed's requests, an example of how you'd call a simple (e.g. ping()) method using async would be really useful.

**Comment by escapewindow** [comment]
How's https://github.com/taskcluster/taskcluster-client.py/pull/83 ?

**Comment by edmorley** [comment]
Left a comment, but otherwise looks great - thank you :-)
