### ISSUE TITLE
Add some smarts for submitting large task graphs

### ISSUE THREAD

**Issue by mozbhearsum** [taskcluster/taskcluster-client.py#84]
I understand that in the new world, clients are responsible for submitting all of their Tasks in the correct order. For large graphs, it can be very tricky to get this right - especially if you have deeply nested dependencies, diamond patterns, and other things that mean it's difficult to efficiently parallelize the submission.

Rather than force various clients to implement this themselves, it seems like it would be helpful to have a function in the client that accepts a large list of tasks, and submits them efficiently.

**Comment by escapewindow** [comment]
Hm, do we still need this? We may want to take the gecko taskgraph code, tear out the gecko-isms, and use that for large taskgraphs.

**Comment by jhford** [comment]
My thinking is that the client library should be limited to making the low level API calls.  I think that having a library which builds on the client library would be a great way to accomplish this in a generic way.
